name: Greetings

on:
  pull_request_target:
    types: [opened, reopened, closed]
  issues:
    types: [opened, closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "👋 Hey there, rockstar! Thanks for dropping an issue! The BlogLog team is on it like pineapple on pizza (love it or hate it). Stick around, magic's about to happen!"
          pr-message: "🎉 Boom! Your pull request just flew into the BlogLog HQ. High fives all around! Our team of tech wizards will check it out and get back to you faster than you can say 'code ninja!' Thanks for leveling up the project!"

  congratulate:
    if: github.event.action == 'closed' && github.event.issue != null
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Congratulate on Issue Closure
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body": "🎉 Congratulations @'${{ github.event.issue.user.login }}'! Your issue has been successfully closed! Thanks for your contribution! If you enjoyed contributing, please consider giving us a ⭐ and following us for updates!"}'
